PETITE_POLICE = ("Verdana",10)
MOYENNE_POLICE = ("Verdana",20)
GRANDE_POLICE = ("Verdana",30,"bold")
TITRE_COLONNE_POLICE = ("Verdana",15,"bold")
VALEUR_LIGNE_POLICE = ("Verdana",10)

TITRE_COLONNE_BACKGROUND = "#659ABD"

TITRE_COLONNE_COULEUR = "#FFFFFF"
VALEUR_LIGNE_COULEUR = "#1E1E1E"